<template>
<div class="table">
  <Collapse accordion v-model="value3"  class="collapse">
    <Panel name='1' class="menu" :hide-arrow="true">
        哲学
        <div slot='content' class="menu2">
            <Collapse accordion>
                <Panel>
                    哲学类
                    <div slot='content'>
                        <table cellspacing="40" class="menu3">
                        <tr>
                        <th>二级学科</th>
                        <th>专业代码</th>
                        <th>专业满意度</th>
                        </tr>
                        <tr>
                        <td>哲学</td>
                        <td>010101</td>
                        <td>4.3</td>
                        </tr>
                        <tr>
                        <td>逻辑学</td>
                        <td>010102</td>
                        <td>3.5</td>
                        </tr>
                        <tr>
                        <td>宗教学</td>
                        <td>010103</td>
                        <td>4.5</td>
                        </tr>
                        <tr>
                        <td>伦理学</td>
                        <td>010103</td>
                        <td>5.0</td>
                        </tr>
                        </table>
                    </div>
                </Panel>
            </Collapse>
        </div>
    </Panel>
    <Panel name="2" class="menu">
        经济学
        <div slot='content' class="menu2">
                <Collapse accordion>
                    <Panel>
                        经济学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>经济学</td>
                            <td>020101</td>
                            <td>4.1</td>
                            </tr>
                            <tr>
                            <td>经济统计学</td>
                            <td>020102</td>
                            <td>4.2</td>
                            </tr>
                            <tr>
                            <td>国民经济管理</td>
                            <td>020103</td>
                            <td>4.3</td>
                            </tr>
                            <tr>
                            <td>资源与环境经济学</td>
                            <td>020104</td>
                            <td>3.7</td>
                            </tr>
                            <tr>
                            <td>商务经济学</td>
                            <td>020105</td>
                            <td>3.9</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        财政学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>财政学</td>
                            <td>020201</td>
                            <td>4.4</td>
                            </tr>
                            <tr>
                            <td>税收学</td>
                            <td>020202</td>
                            <td>4.4</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        金融学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>金融学</td>
                            <td>020301</td>
                            <td>4.3</td>
                            </tr>
                            <tr>
                            <td>金融工程</td>
                            <td>020302</td>
                            <td>4.3</td>
                            </tr>
                            <tr>
                            <td>保险学</td>
                            <td>020303</td>
                            <td>4.2</td>
                            </tr>
                            <tr>
                            <td>投资学</td>
                            <td>020304</td>
                            <td>4.2</td>
                            </tr>
                            <tr>
                            <td>金融数学</td>
                            <td>020305</td>
                            <td>4.4</td>
                            </tr>
                            <tr>
                            <td>信用管理</td>
                            <td>020306</td>
                            <td>4.3</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        经济与贸易类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>国际经济与贸易</td>
                            <td>020401</td>
                            <td>4.1</td>
                            </tr>
                            <tr>
                            <td>贸易经济</td>
                            <td>020402</td>
                            <td>4.2</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                </Collapse>
            </div>
    </Panel>
    <Panel name="3" class="menu">
        法学
        <div slot='content' class="menu2">
                <Collapse accordion>
                    <Panel>
                        法学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>法学</td>
                            <td>030101</td>
                            <td>4.3</td>
                            </tr>
                            <tr>
                            <td>知识产权</td>
                            <td>030102</td>
                            <td>4.1</td>
                            </tr>
                            <tr>
                            <td>监狱学</td>
                            <td>030103</td>
                            <td>4.3</td>
                            </tr>
                            <tr>
                            <td>信用风险管理与法律防控</td>
                            <td>030104</td>
                            <td>4.0</td>
                            </tr>
                            <tr>
                            <td>国际经贸规则</td>
                            <td>030105</td>
                            <td>4.3</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                     <Panel>
                        政治学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>政治学与行政学</td>
                            <td>030201</td>
                            <td>3.9</td>
                            </tr>
                            <tr>
                            <td>国际政治</td>
                            <td>030202</td>
                            <td>3.9</td>
                            </tr>
                            <tr>
                            <td>外交学</td>
                            <td>030203</td>
                            <td>3.7</td>
                            </tr>
                            <tr>
                            <td>国际事务与国际关系</td>
                            <td>030204</td>
                            <td>4.2</td>
                            </tr>
                            <tr>
                            <td>政治学、经济学与哲学</td>
                            <td>030205</td>
                            <td>3.7</td>
                            </tr>
                            <tr>
                            <td>国际组织与全球治理</td>
                            <td>030206</td>
                            <td>3.7</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                     <Panel>
                        社会学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>社会学</td>
                            <td>030301</td>
                            <td>4.0</td>
                            </tr>
                            <tr>
                            <td>社会工作</td>
                            <td>030302</td>
                            <td>3.9</td>
                            </tr>
                            <tr>
                            <td>人类学</td>
                            <td>030303</td>
                            <td>4.1</td>
                            </tr>
                            <tr>
                            <td>女性学</td>
                            <td>030304</td>
                            <td>4.0</td>
                            </tr>
                            <tr>
                            <td>家政学</td>
                            <td>030305</td>
                            <td>4.0</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                </Collapse>
            </div>
    </Panel>
    <Panel name="4" class="menu">
        教育学
        <div slot='content' class="menu2">
                <Collapse accordion>
                    <Panel>
                        教育学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>教育学</td>
                            <td>040101</td>
                            <td>3.9</td>
                            </tr>
                            <tr>
                            <td>科学教育</td>
                            <td>040102</td>
                            <td>3.9</td>
                            </tr>
                            <tr>
                            <td>人文教育</td>
                            <td>040103</td>
                            <td>3.7</td>
                            </tr>
                            <tr>
                            <td>教育技术学</td>
                            <td>040104</td>
                            <td>3.7</td>
                            </tr>
                            <tr>
                            <td>艺术教育</td>
                            <td>040105</td>
                            <td>3.9</td>
                            </tr>
                            <tr>
                            <td>学前教育</td>
                            <td>040106</td>
                            <td>4.4</td>
                            </tr>
                            <tr>
                            <td>小学教育</td>
                            <td>040107</td>
                            <td>4.2</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                     <Panel>
                        体育学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>体育教育</td>
                            <td>040201</td>
                            <td>4.4</td>
                            </tr>
                            <tr>
                            <td>运动训练</td>
                            <td>040202</td>
                            <td>4.6</td>
                            </tr>
                            <tr>
                            <td>社会体育指导与管理</td>
                            <td>040203</td>
                            <td>4.1</td>
                            </tr>
                            <tr>
                            <td>武术与民族传统体育</td>
                            <td>040204</td>
                            <td>4.6</td>
                            </tr>
                            <tr>
                            <td>运动人体科学</td>
                            <td>040205</td>
                            <td>3.6</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                </Collapse>
            </div>
    </Panel>
    <Panel name="5" class="menu">
        文学
        <div slot='content' class="menu2">
                <Collapse accordion>
                    <Panel>
                        中国语言文学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>汉语言文学</td>
                            <td>050101</td>
                            <td>4.4</td>
                            </tr>
                            <tr>
                            <td>汉语言</td>
                            <td>050102</td>
                            <td>4.1</td>
                            </tr>
                            <tr>
                            <td>汉语国际教育</td>
                            <td>050103</td>
                            <td>3.8</td>
                            </tr>
                            <tr>
                            <td>中国少数民族语言文学</td>
                            <td>050104</td>
                            <td>4.2</td>
                            </tr>
                            <tr>
                            <td>古典文献学</td>
                            <td>050105</td>
                            <td>4.2</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                     <Panel>
                        外国语言文学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>英语</td>
                            <td>050201</td>
                            <td>4.0</td>
                            </tr>
                            <tr>
                            <td>俄语</td>
                            <td>050202</td>
                            <td>4.3</td>
                            </tr>
                            <tr>
                            <td>德语</td>
                            <td>050203</td>
                            <td>4.0</td>
                            </tr>
                            <tr>
                            <td>法语</td>
                            <td>050204</td>
                            <td>4.2</td>
                            </tr>
                            <tr>
                            <td>西班牙语</td>
                            <td>050205</td>
                            <td>4.3</td>
                            </tr>
                            <tr>
                            <td>阿拉伯语</td>
                            <td>050206</td>
                            <td>4.4</td>
                            </tr>
                            <tr>
                            <td>日语</td>
                            <td>050207</td>
                            <td>4.1</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                     <Panel>
                        新闻传播学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>新闻学</td>
                            <td>050301</td>
                            <td>4.0</td>
                            </tr>
                            <tr>
                            <td>广播电视学</td>
                            <td>050302</td>
                            <td>4.0</td>
                            </tr>
                            <tr>
                            <td>广告学</td>
                            <td>050303</td>
                            <td>4.1</td>
                            </tr>
                            <tr>
                            <td>传播学</td>
                            <td>050304</td>
                            <td>4.0</td>
                            </tr>
                            <tr>
                            <td>编辑出版学</td>
                            <td>050305</td>
                            <td>4.0</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                </Collapse>
            </div>
    </Panel>
    <Panel name="6" class="menu">
        历史学
        <div slot='content' class="menu2">
                <Collapse accordion>
                    <Panel>
                        历史学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>历史学</td>
                            <td>060101</td>
                            <td>4.2</td>
                            </tr>
                            <tr>
                            <td>世界史</td>
                            <td>060102</td>
                            <td>4.2</td>
                            </tr>
                            <tr>
                            <td>考古学</td>
                            <td>060103</td>
                            <td>4.5</td>
                            </tr>
                            <tr>
                            <td>文物与博物馆学</td>
                            <td>060104</td>
                            <td>4.0</td>
                            </tr>
                            <tr>
                            <td>文物保护技术</td>
                            <td>060105</td>
                            <td>3.9</td>
                            </tr>
                            <tr>
                            <td>外国语言与外国历史</td>
                            <td>060106</td>
                            <td>5.0</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                </Collapse>
            </div>
    </Panel>
    <Panel name="7" class="menu">
        理学
        <div slot='content' class="menu2">
                <Collapse accordion>
                    <Panel>
                        数学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>数学与应用数学</td>
                            <td>070101</td>
                            <td>4.2</td>
                            </tr>
                            <tr>
                            <td>信息与计算科学</td>
                            <td>070102</td>
                            <td>3.8</td>
                            </tr>
                            <tr>
                            <td>数理基础科学</td>
                            <td>070103</td>
                            <td>4.3</td>
                            </tr>
                            <tr>
                            <td>数据计算及应用</td>
                            <td>070104</td>
                            <td>4.2</td>
                            </tr>
                            <tr>
                            <td>哲学</td>
                            <td>010101</td>
                            <td>300</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                     <Panel>
                        物理学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>物理学</td>
                            <td>070201</td>
                            <td>4.2</td>
                            </tr>
                            <tr>
                            <td>应用物理学</td>
                            <td>070202</td>
                            <td>3.7</td>
                            </tr>
                            <tr>
                            <td>核物理</td>
                            <td>070203</td>
                            <td>4.3</td>
                            </tr>
                            <tr>
                            <td>声学</td>
                            <td>070204</td>
                            <td>4.8</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                     <Panel>
                        化学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>化学</td>
                            <td>070301</td>
                            <td>4.2</td>
                            </tr>
                            <tr>
                            <td>应用化学</td>
                            <td>070302</td>
                            <td>4.0</td>
                            </tr>
                            <tr>
                            <td>化学生物学</td>
                            <td>070303</td>
                            <td>3.9</td>
                            </tr>
                            <tr>
                            <td>分子科学与工程</td>
                            <td>070304</td>
                            <td>4.3</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                     <Panel>
                        天文学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>天文学</td>
                            <td>070401</td>
                            <td>4.4</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                     <Panel>
                        地理科学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>地理科学</td>
                            <td>070501</td>
                            <td>4.3</td>
                            </tr>
                            <tr>
                            <td>自然地理与资源环境</td>
                            <td>070502</td>
                            <td>3.5</td>
                            </tr>
                            <tr>
                            <td>人文地理与城乡规划</td>
                            <td>070503</td>
                            <td>3.6</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                     <Panel>
                        大气科学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>大气科学</td>
                            <td>070601</td>
                            <td>4.4</td>
                            </tr>
                            <tr>
                            <td>应用气象学</td>
                            <td>070602</td>
                            <td>4.2</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                     <Panel>
                        海洋科学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>海洋科学</td>
                            <td>070701</td>
                            <td>3.6</td>
                            </tr>
                            <tr>
                            <td>海洋技术</td>
                            <td>070702</td>
                            <td>3.5</td>
                            </tr>
                            <tr>
                            <td>海洋资源与环境</td>
                            <td>070703</td>
                            <td>3.9</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                     <Panel>
                        地球物理学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>地球物理学</td>
                            <td>070801</td>
                            <td>4.0</td>
                            </tr>
                            <tr>
                            <td>哲学</td>
                            <td>空间科学与技术</td>
                            <td>4.1</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                     <Panel>
                        地质学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>地质学</td>
                            <td>070901</td>
                            <td>4.0</td>
                            </tr>
                            <tr>
                            <td>地球化学</td>
                            <td>070902</td>
                            <td>3.9</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                     <Panel>
                        生物科学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>生物科学</td>
                            <td>071001</td>
                            <td>4.0</td>
                            </tr>
                            <tr>
                            <td>生物技术</td>
                            <td>071002</td>
                            <td>3.7</td>
                            </tr>
                            <tr>
                            <td>生物信息学</td>
                            <td>071003</td>
                            <td>3.9</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                     <Panel>
                        心理学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>心理学</td>
                            <td>071101</td>
                            <td>4.2</td>
                            </tr>
                            <tr>
                            <td>应用心理学</td>
                            <td>071102</td>
                            <td>4.0</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                     <Panel>
                        统计学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>统计学</td>
                            <td>071201</td>
                            <td>4.2</td>
                            </tr>
                            <tr>
                            <td>应用统计学</td>
                            <td>071202</td>
                            <td>4.3</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                </Collapse>
            </div>
    </Panel>
    <Panel name="8" class="menu">
        工学
        <div slot='content' class="menu2">
                <Collapse accordion>
                    <Panel>
                        力学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>理论与应用力学</td>
                            <td>080101</td>
                            <td>3.9</td>
                            </tr>
                            <tr>
                            <td>工程力学</td>
                            <td>080102</td>
                            <td>4.1</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        机械类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>机械工程</td>
                            <td>080201</td>
                            <td>4.1</td>
                            </tr>
                            <tr>
                            <td>机械设计制造及其自动化</td>
                            <td>080202</td>
                            <td>4.2</td>
                            </tr>
                            <tr>
                            <td>材料成型及控制工程</td>
                            <td>080203</td>
                            <td>4.2</td>
                            </tr>
                            <tr>
                            <td>机械电子工程</td>
                            <td>080204</td>
                            <td>4.1</td>
                            </tr>
                            <tr>
                            <td>工业设计</td>
                            <td>080205</td>
                            <td>3.9</td>
                            </tr>
                            <tr>
                            <td>车辆工程</td>
                            <td>080206</td>
                            <td>4.0</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        仪器类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>测控技术与仪器</td>
                            <td>080301</td>
                            <td>4.1</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        材料类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>材料科学与工程</td>
                            <td>080401</td>
                            <td>4.1</td>
                            </tr>
                            <tr>
                            <td>材料物理</td>
                            <td>080402</td>
                            <td>3.8</td>
                            </tr>
                            <tr>
                            <td>材料化学</td>
                            <td>080403</td>
                            <td>4.0</td>
                            </tr>
                            <tr>
                            <td>冶金工程</td>
                            <td>080404</td>
                            <td>4.1</td>
                            </tr>
                            <tr>
                            <td>金属材料工程</td>
                            <td>080405</td>
                            <td>3.9</td>
                            </tr>
                            <tr>
                            <td>无机非金属材料工程</td>
                            <td>080406</td>
                            <td>4.0</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        能源动力类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>能源与动力工程</td>
                            <td>080501</td>
                            <td>4.1</td>
                            </tr>
                            <tr>
                            <td>能源与环境系统工程</td>
                            <td>080502</td>
                            <td>4.0</td>
                            </tr>
                            <tr>
                            <td>新能源科学与工程</td>
                            <td>080503</td>
                            <td>3.9</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        电子类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>电气工程及其自动化</td>
                            <td>080601</td>
                            <td>4.4</td>
                            </tr>
                            <tr>
                            <td>智能电网信息工程</td>
                            <td>080602</td>
                            <td>4.5</td>
                            </tr>
                            <tr>
                            <td>光源与照明</td>
                            <td>080603</td>
                            <td>3.9</td>
                            </tr>
                            <tr>
                            <td>电气工程与智能控制</td>
                            <td>080604</td>
                            <td>4.4</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        自动化类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>自动化</td>
                            <td>080801</td>
                            <td>4.2</td>
                            </tr>
                            <tr>
                            <td>轨道交通信号与控制</td>
                            <td>080802</td>
                            <td>3.9</td>
                            </tr>
                            <tr>
                            <td>机器人工程</td>
                            <td>080803</td>
                            <td>3.8</td>
                            </tr>
                            <tr>
                            <td>邮政工程</td>
                            <td>080804</td>
                            <td>4.1</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        计算机类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>计算机科学与技术</td>
                            <td>080901</td>
                            <td>4.9</td>
                            </tr>
                            <tr>
                            <td>软件工程</td>
                            <td>080902</td>
                            <td>4.9</td>
                            </tr>
                            <tr>
                            <td>网络工程</td>
                            <td>080903</td>
                            <td>4.7</td>
                            </tr>
                            <tr>
                            <td>信息安全</td>
                            <td>080904</td>
                            <td>4.7</td>
                            </tr>
                            <tr>
                            <td>物联网工程</td>
                            <td>080905</td>
                            <td>4.0</td>
                            </tr>
                            <tr>
                            <td>数字媒体技术</td>
                            <td>080906</td>
                            <td>3.9</td>
                            </tr>
                            <tr>
                            <td>智能科学与技术</td>
                            <td>080907</td>
                            <td>4.3</td>
                            </tr>
                            <tr>
                            <td>空间信息与数字技术</td>
                            <td>080908</td>
                            <td>4.1</td>
                            </tr>
                            <tr>
                            <td>电子与计算机工程</td>
                            <td>080909</td>
                            <td>4.2</td>
                            </tr>
                            <tr>
                            <td>数据科学与大数据技术</td>
                            <td>080910</td>
                            <td>4.8</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        土木类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>土木工程</td>
                            <td>081001</td>
                            <td>4.4</td>
                            </tr>
                            <tr>
                            <td>建筑环境与能源应用工程</td>
                            <td>081002</td>
                            <td>4.3</td>
                            </tr>
                            <tr>
                            <td>给排水科学与工程</td>
                            <td>081003</td>
                            <td>4.4</td>
                            </tr>
                            <tr>
                            <td>建筑电气与智能化</td>
                            <td>081004</td>
                            <td>4.3</td>
                            </tr>
                            <tr>
                            <td>城市地下空间工程</td>
                            <td>081005</td>
                            <td>4.4</td>
                            </tr>
                            <tr>
                            <td>道路桥梁与渡河工程</td>
                            <td>081006</td>
                            <td>4.5</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        水利类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>水利水电工程</td>
                            <td>081101</td>
                            <td>4.3</td>
                            </tr>
                            <tr>
                            <td>水文与水资源工程</td>
                            <td>081102</td>
                            <td>4.1</td>
                            </tr>
                            <tr>
                            <td>港口航道与海岸工程</td>
                            <td>081103</td>
                            <td>4.3</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        测绘类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>测绘工程</td>
                            <td>081201</td>
                            <td>4.3</td>
                            </tr>
                            <tr>
                            <td>遥感科学与技术</td>
                            <td>081202</td>
                            <td>4.2</td>
                            </tr>
                            <tr>
                            <td>导航工程</td>
                            <td>081203</td>
                            <td>4.4</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        化工与制药类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>化学工程与工艺</td>
                            <td>081301</td>
                            <td>4.4</td>
                            </tr>
                            <tr>
                            <td>制药工程</td>
                            <td>081302</td>
                            <td>4.3</td>
                            </tr>
                            <tr>
                            <td>资源循环科学与工程</td>
                            <td>081303</td>
                            <td>4.2</td>
                            </tr>
                            <tr>
                            <td>能源化学工程</td>
                            <td>081304</td>
                            <td>4.4</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        地质类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>地质工程</td>
                            <td>081401</td>
                            <td>4.1</td>
                            </tr>
                            <tr>
                            <td>勘查技术与工程</td>
                            <td>081402</td>
                            <td>4.3</td>
                            </tr>
                            <tr>
                            <td>资源勘查工程</td>
                            <td>081403</td>
                            <td>4.2</td>
                            </tr>
                            <tr>
                            <td>地下水科学与工程</td>
                            <td>081404</td>
                            <td>4.4</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        环境科学与工程类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>环境科学与工程</td>
                            <td>082501</td>
                            <td>4.2</td>
                            </tr>
                            <tr>
                            <td>环境工程</td>
                            <td>082502</td>
                            <td>3.9</td>
                            </tr>
                            <tr>
                            <td>环境科学</td>
                            <td>082503</td>
                            <td>4.2</td>
                            </tr>
                            <tr>
                            <td>环境生态工程</td>
                            <td>082504</td>
                            <td>4.4</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                </Collapse>
            </div>
    </Panel>
    <Panel name="9" class="menu">
        农学
        <div slot='content' class="menu2">
                <Collapse accordion>
                    <Panel>
                        植物生产类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>农学</td>
                            <td>090101</td>
                            <td>4.1</td>
                            </tr>
                            <tr>
                            <td>园艺</td>
                            <td>090102</td>
                            <td>3.9</td>
                            </tr>
                            <tr>
                            <td>植物保护</td>
                            <td>090103</td>
                            <td>4.1</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        自然保护与环境生态类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>农业资源与环境</td>
                            <td>090201</td>
                            <td>3.8</td>
                            </tr>
                            <tr>
                            <td>野生动物与自然保护区管理</td>
                            <td>090202</td>
                            <td>3.9</td>
                            </tr>
                            <tr>
                            <td>水土保持与荒漠化防治</td>
                            <td>090203</td>
                            <td>3.8</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        动物生产类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>动物科学</td>
                            <td>090301</td>
                            <td>4.1</td>
                            </tr>
                            <tr>
                            <td>蚕学</td>
                            <td>090302</td>
                            <td>3.4</td>
                            </tr>
                            <tr>
                            <td>蜂学</td>
                            <td>090303</td>
                            <td>3.5</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                </Collapse>
            </div>
    </Panel>
    <Panel name="10" class="menu">
        医学
        <div slot='content' class="menu2">
                <Collapse accordion>
                    <Panel>
                        基础医学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>基础医学</td>
                            <td>100101</td>
                            <td>3.3</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        临床医学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>临床医学</td>
                            <td>100201</td>
                            <td>4.2</td>
                            </tr>
                            <tr>
                            <td>麻醉学</td>
                            <td>100202</td>
                            <td>4.4</td>
                            </tr>
                            <tr>
                            <td>医学影像学</td>
                            <td>100203</td>
                            <td>4.4</td>
                            </tr>
                            <tr>
                            <td>眼视光医学</td>
                            <td>100204</td>
                            <td>4.5</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        口腔医学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>口腔医学</td>
                            <td>100301</td>
                            <td>4.4</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        中医学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>中医学</td>
                            <td>100501</td>
                            <td>3.9</td>
                            </tr>
                            <tr>
                            <td>针灸推拿学</td>
                            <td>100502</td>
                            <td>4.2</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        药学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>药学</td>
                            <td>100701</td>
                            <td>4.2</td>
                            </tr>
                            <tr>
                            <td>药物制剂</td>
                            <td>100702</td>
                            <td>4.1</td>
                            </tr>
                            <tr>
                            <td>临床药学</td>
                            <td>100703</td>
                            <td>4.0</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                </Collapse>
            </div>
    </Panel>
    <Panel name="11" class="menu">
        管理学
        <div slot='content' class="menu2">
                <Collapse accordion>
                    <Panel>
                        管理科学与工程类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>管理科学</td>
                            <td>120101</td>
                            <td>3.9</td>
                            </tr>
                            <tr>
                            <td>信息管理与信息系统</td>
                            <td>120102</td>
                            <td>3.8</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        工商管理类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>工商管理</td>
                            <td>120201</td>
                            <td>4.3</td>
                            </tr>
                            <tr>
                            <td>市场营销</td>
                            <td>120202</td>
                            <td>4.2</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        公共管理类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>公共事业管理</td>
                            <td>120401</td>
                            <td>3.7</td>
                            </tr>
                            <tr>
                            <td>行政管理</td>
                            <td>120402</td>
                            <td>4.2</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        图书情报与档案管理类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>图书馆学</td>
                            <td>120501</td>
                            <td>4.0</td>
                            </tr>
                            <tr>
                            <td>档案学</td>
                            <td>120502</td>
                            <td>4.2</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                </Collapse>
            </div>
    </Panel>
    <Panel name="12" class="menu">
        艺术学
        <div slot='content' class="menu2">
                <Collapse accordion>
                    <Panel>
                        艺术学理论类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>艺术史论</td>
                            <td>130101</td>
                            <td>3.8</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        音乐与舞蹈学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>音乐表演</td>
                            <td>130201</td>
                            <td>4.3</td>
                            </tr>
                            <tr>
                            <td>音乐学</td>
                            <td>130202</td>
                            <td>4.3</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        戏剧与影视学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>表演</td>
                            <td>130301</td>
                            <td>4.2</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        美术学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>美术学</td>
                            <td>130401</td>
                            <td>4.3</td>
                            </tr>
                            <tr>
                            <td>绘画</td>
                            <td>130402</td>
                            <td>4.3</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                    <Panel>
                        设计学类
                        <div slot='content'>
                            <table cellspacing="40" class="menu3">
                            <tr>
                            <th>二级学科</th>
                            <th>专业代码</th>
                            <th>专业满意度</th>
                            </tr>
                            <tr>
                            <td>艺术设计学</td>
                            <td>130501</td>
                            <td>3.9</td>
                            </tr>
                            </table>
                        </div>
                    </Panel>
                </Collapse>
            </div>
    </Panel>
  </Collapse>
</div>
</template>
<script>
    export default {
      data () {
        return {
        }
      }
    }
</script>
<style>
  .menu {
    text-indent:20px;
    font-size:24px;
  }
  .menu2 {
    text-indent:40px;
    font-size:20px;
    
  }
  .menu3 {
    text-indent:160px;
    font-size:16px;
  }

  .collapse
    {
        background-color:#fff;
        position: relative;
        top: 25px;
    }
    td
    {
	    text-align: center;
    }
    th
    {
	    text-align: center;
    }

.ivu-icon-arrow-right-b:before{
    content:""
}
</style>